export default {
  // url: "https://rhqx4pwf-5100.inc1.devtunnels.ms/api",
  url: "http://localhost:5100/api",
  endpoints: {
    auth: {
      login: "/auth/login",
      signup: "/auth/signup",
      getOtp: "/auth/get-otp",
      verifyOtp: "/auth/verify-otp",
    },
    user: {
      details: "/user/details",
      updateProfile: "/user/updateProfile",
      updateAvatar: "/user/updateAvatar",
      addProject: "/user/addProject",
      updateProject: "/user/updateProject",
      projectImages: "/user/projectImages",
      addEducation: "/user/addEducation",
      updateEducation: "/user/updateEducation",
      addCourse: "/user/addCourse",
      updateCourse: "/user/updateCourse",
      addCoursePreview: "/user/addCoursePreview",
      addCertification: "/user/addCertification",
      updateCertification: "/user/updateCertification",
      addCertificationPreview: "/user/addCertificationPreview",
      addCompetition: "/user/addCompetition",
      updateCompetition: "/user/updateCompetition",
      addCompetitionPreview: "/user/addCompetitionPreview",
      addExtracurricular: "/user/addExtracurricular",
      updateExtracurricular: "/user/updateExtracurricular",
    },
  },
};
